### PR TITLE
quick fix to make this work

### PR DESCRIPTION
**Pull request by andrewprivate**
1. Removed `ww3` because that part changes too often
2. Fixed source getting
3. Video sources now have two types. `iframe` and `source`.

PS: VSC auto-formatted

PPS: I know this is years old, I dont expect this PR to be merged. But this will still be helpful to anyone who wants to use this.

EDIT: That was fast...

### CODE REVIEW

**Comment by roflmuffin** [comment]
Hey Andrew, thanks for the PR. I don't have time to test this myself, but if its working for you then I will approve & merge this.

One change before that however, can you increment the package version in the package.json to 3.1.0 and I will merge & publish to npm.

**Comment by andrewprivate** [comment]
Wow, that was fast. Updated version for you!

**Comment by andrewprivate** [comment]
Heres a pic with the readme snippet.

```js
var Anime = require('anime-scraper').Anime
Anime.fromName('Haikyuu!!').then(function (anime) {
    anime.episodes[0].fetch().then(function (episode) {
        console.log(episode)
    })
})
```

Screen Shot 2019-05-19 at 11 05 12 PM

**Comment by roflmuffin** [comment]
Thanks for this Andrew, that should be published to the npm registry now!

**Comment by andrewprivate** [comment]
Your welcome! Glad I could help.

**Pull request merged**
